server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Study/MSA/native-file-repo
        git:
          uri: https://github.com/SPRING-STUDY-2023/sohyeon-spring-cloud-config.git
#           private Repository 로 설정했을 경우 username, password 추가
#          username: [your username]
#          password: [your password]
#          uri: file:///Users/sohyeon/Study/MSA/git-local-repo # pwd로 경로 확인 가능

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh